### ISSUE TITLE
doc link to CSP config management is broken

### ISSUE THREAD

**Issue by pingvishal** [GoogleCloudPlatform/csp-config-management#1]
https://cloud.google.com/csp-config-management/docs/ is referred at multiple places and returns HTTP 404.
- https://github.com/GoogleCloudPlatform/csp-config-management/blob/master/README.md refers to https://cloud.google.com/csp-config-management/docs/
- https://github.com/GoogleCloudPlatform/csp-config-management/tree/master/foo-corp refers to https://cloud.google.com/csp-config-management/docs/quickstart

**Comment by HardySimpson** [comment]
same question, hope someone come to fix

**Comment by willbeason** [comment]
These doc links have since been fixed. (The pages are now correctly redirect)
