### ISSUE TITLE
Remove HierarchyConfig and virtual resource quota?

### ISSUE THREAD

**Issue by bmenasha** [GoogleCloudPlatform/csp-config-management#10]
I think these two files are artifacts of Aggregated Resource Quota which is no longer in Anthos Config Managment and should be deleted.  I don't see any corresponding resources in my cluster that represent these objects so I think they are ignored and will just confuse readers who seek to understand this example.

csp-config-management/foo-corp/namespaces/online/shipping-app-backend/quota.yaml  
csp-config-management/foo-corp/system/resourcequota-hierarchy.yaml

Also renaming this repository to anthos-config-management will improve search-ability and brand compliance. 
thanks

**Comment by frankfarzan** [comment]
The concept of HierarchyConfig is still relevant, and documented here:

https://cloud.google.com/anthos-config-management/docs/how-to/namespace-scoped-objects#disabling_inheritance_for_an_object_type

So this bug should be about just removing csp-config-management/foo-corp/system/resourcequota-hierarchy.yaml
which defaults to behavior of "inherit" (copy-down semantics).

ResourceQuota would then be inherited by prod,staging,dev namespaces in shipping-app-backend.

This is done here:

https://github.com/GoogleCloudPlatform/csp-config-management/commit/283b52c71600bee23379bad7aed168c38a5ded68
