### ISSUE TITLE
Deploying resources dependent upon CRDs fails

### ISSUE THREAD

**Issue by reiimer** [GoogleCloudPlatform/csp-config-management#13]
How would you deploy for example prometheus operator with config sync [Manual guide](https://cloud.google.com/kubernetes-engine/docs/add-on/config-sync/how-to/monitoring)
The problem is that the CRD is created by the operator and not resolvable by config sync during the initial sync when trying to deploy from a repository containing prometheus objects config sync will complain with the following error:
```
[1] KNV1021: No CustomResourceDefinition is defined for the type "Prometheus.monitoring.coreos.com" in the cluster.
Resource types that are not native Kubernetes objects must have a CustomResourceDefinition.

source: namespaces/monitoring/monitoring-namespaced-resources.yaml
namespace: monitoring
metadata.name: acm
group: monitoring.coreos.com
version: v1
kind: Prometheus
```

The same is also true when trying to deploy gatekeeper with gatekeeper policies in the same repo.

**Comment by willbeason** [comment]
That's a great question! We encountered this problem when integrating with Gatekeeper to make [Policy Controller](https://cloud.google.com/anthos-config-management/docs/concepts/policy-controller). Specifically, we made an exception just for Gatekeeper types.

Right now we fail-early when we encounter definitions for types that the API Server doesn't yet recognize, which causes this issue. We try to apply the repository atomically, so if one object fails validation we don't try to apply anything. This prevents us from ever applying the configuration that *would* heal itself as the appropriate controllers would make/apply the expected CRDs.

I don't immediately see why we're doing that (in this instance) as - at worst - applying a CR whose type the API Server doesn't recognize returns an error that would be surfaced to the user anyways. I'll ask around.

**Comment by jrmurray000** [comment]
We're tracking this issue internally and will provide an update in a forthcoming release. Closing this ticket, as we're only using this issue queue to track items related to the examples provided in the repository.

Feel free to reach out to me at johnmurray@google.com if you'd like more info on our plans.
